### PR TITLE
Allow the build to be reproducible and to make use of hardening flags

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by tohojo** [comment]
Thank you for the fixes!

The man pages are exported from the README.org files in each directory, so just editing them like you're doing in your first commit won't work, unfortunately. Some hacking of the emacs org-mode export is probably needed for fixing this.

**Comment by bluca** [comment]
Ok, I've dropped that commit

**Comment by tohojo** [comment]
Could you please confirm that #212 fixes the man page issue?

**Comment by bluca** [comment]
> Could you please confirm that #212 fixes the man page issue?

Yes, thank you!

**Pull request merged**
