### PR TITLE
Makefile: git submodule detect and warn if out-of-sync

### PR DESCRIPTION
**Pull request by netoptimizer**
It is a reoccuring issue that git submodule gets out-of-sync, which cause confusion and issues.

 End-user needs to run:  git submodule update

We cannot run this automatically, because there are legimite reasons for the submodule to be out-of-sync, e.g. when testing local changes.

Thus, this patch detect SHA-1 doesn't match, and just warns end-users, together with a hint to call: git submodule update

### CODE REVIEW

**Comment by netoptimizer** [comment]
Per discussion in PR #18

**Comment by tohojo** [comment]
Erm, GitHub seems to think the commit is empty?

**Comment by netoptimizer** [comment]
> Erm, GitHub seems to think the commit is empty?

LOL - It seems I forgot got call ```stg refresh``` get changes integrated, usually [stgit](http://www.procode.org/stgit/) warns on different operations when having uncommitted changes, but I've tried the ```stg publish``` which didn't warn me.

**Comment by netoptimizer** [comment]
I fixed it in the stg branch, and ran `stg publish` again.  This resulted in two commit's one empty and the new with same text and contents. I'll try push a new branch, with a clean history.

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

> I fixed it in the stg branch, and ran `stg publish` again.  This
> resulted in two commit's one empty and the new with same text and
> contents. I'll try push a new branch, with a clean history.

No worries, I can squash those when merging; going to do a bit of
cleanup of the Makefile anyway :)

**Comment by netoptimizer** [comment]
I will close this one, in favor of PR #21

**Pull request closed without merging**
