### PR TITLE
Fix libxdp build and linking errors

### LINKED ISSUE #135: Error when linking with libxdp
When linking with libxdp, two errors are generated:
```
cc -Wl,--no-as-needed -lxdp
/usr/bin/ld: /usr/local/lib/libxdp.so: undefined reference to `try_snprintf'
/usr/bin/ld: /usr/local/lib/libxdp.so: undefined reference to `silence_libbpf_logging'
```

objdump confirms they are undefined:
```
objdump -t /usr/local/lib/libxdp.so | grep try_snprintf
000000000000a710 l F .text 00000000000000da try_snprintf
0000000000000000 *UND* 0000000000000000 try_snprintf

objdump -t /usr/local/lib/libxdp.so | grep silence_libbpf
0000000000000000 *UND* 0000000000000000 silence_libbpf_logging
```

The call to try_snprintf was introduced to xsk.c in:
fdd1566dcd1f ("libxdp: get queue num from sysfs in xsk")

The call to silence_libbpf_logging in xsk.c was introduced in:
ea481a18ed07 ("libxdp: move AF_XDP functionality from libbpf")

### PR DESCRIPTION
**Pull request by tohojo**
Fix a couple of build and link errors for libxdp, and add a selftest to make
sure they don't resurface.

Fixes #135.

### CODE REVIEW

**Review by magnus-karlsson — APPROVED** [review]
Thanks for the fixing Toke. Removing the silence_libbpf_logging() will likely make libbpf barf out confusing messages to the user. I believe that is why I put it there in the first place. But I agree that we should try to use default libbpf settings. Let us see what Ciara says for her DPDK use case.

**Comment by tohojo** [comment]
Right, we may want to add a way for users of the library to opt-in to libxdp taking over (and silencing) the libbpf logging. But doing it unconditionally is a bit rude I think ;)

**Comment by cloftus** [comment]
Thanks for fixing @tohojo 

Some new libbpf logs pop up when using libxdp with DPDK:
libbpf: elf: skipping unrecognized data section(7) .xdp_run_config
libbpf: elf: skipping unrecognized data section(8) xdp_metadata
libbpf: elf: skipping unrecognized data section(8) xdp_metadata
libbpf: elf: skipping unrecognized data section(8) xdp_metadata

It would be nice to have the option to suppress those eventually.

**Comment by tohojo** [comment]
Ugh, yeah, those are annoying... will see if we can figure out a way to silence those that are not too intrusive...

**Comment by tohojo** [comment]
Hmm, we could add a new flag `XSK_LIBXDP_FLAGS__VERBOSE_LOGGING` and silence the logging unless this is set? Or we could try to install a filter function and filter out those particular messages but keep everything else intact? Is libbpf logs something people who use XSKs are generally interested in (for debugging)? And if so how do they get at them?

**Comment by magnus-karlsson** [comment]
In the libbpf version, the logging is not silenced as it does not print the
warnings that we get with libxdp. Just silencing those warnings would be
helpful.

**Comment by tohojo** [comment]
Actually for that particular error message I think the right thing to do is fix libbpf to not emit it. I seem to recall having such a patch rejected before, but with a more concrete reason for it maybe it'll fly; will give it a shot and otherwise look into filtering...

**Comment by tohojo** [comment]
Submitted here: https://lore.kernel.org/r/20211104122911.779034-1-toke@redhat.com

**Pull request merged**
