### PR TITLE
Fix #184

### LINKED ISSUE #184: xdp fails to attach dispatcher
And unfortunately doesn't fall back to single program mode.

```
libbpf: elf: skipping unrecognized data section(7) .xdp_run_config
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
libbpf: prog 'xdp_dispatcher': BPF program load failed: Invalid argument
libbpf: prog 'xdp_dispatcher': -- BEGIN PROG LOAD LOG --
Validating prog0() func#1...
btf_vmlinux is malformed
Arg#0 type PTR in prog0() is not supported yet.
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
-- END PROG LOAD LOG --
libbpf: failed to load program 'xdp_dispatcher'
libbpf: failed to load object './xdp-dispatcher.o'
libxdp: Failed to load dispatcher: Invalid argument
```

Kernel version is: 5.10.109

### PR DESCRIPTION
**Pull request by gizahNL**

### CODE REVIEW

**Comment by tohojo** [comment]
Let's fix the check inside `xdp_multiprog__load()` instead. Since libbpf removed `LIBPF_ERRNO__VERIFY` entirely, I guess we'll have to just turn any error into the EOPNOTSUPP that generates the fallback...

**Comment by tohojo** [comment]
Also, please add a proper commit message describing the issue+fix (so that the commit log makes sense without having to refer to github)

**Comment by gizahNL** [comment]
ptal

**Comment by tohojo** [comment]
Change looks good, but seems you accidentally included a backup file for the man page in the commit... :)

**Comment by gizahNL** [comment]
> Change looks good, but seems you accidentally included a backup file for the man page in the commit... :)

Sigh... I had too little coffee.. Let me correct it ;)

**Comment by tohojo** [comment]
That's better, thanks!

**Review by tohojo — APPROVED** [review]

**Pull request merged**
