### PR TITLE
fix program_is_loaded() so it will not close fd 0

### PR DESCRIPTION
**Pull request by chaudron**
program_is_loaded() would close file descriptor 0, this patch avoids
it. Closing FD 0 in my scenario was causing a "No such file or
directory" error when trying to bpf_object__load() an object
which has the .attach_prog_fd attribute set.

### CODE REVIEW

**Comment by chaudron** [comment]
This causes me a day of experimenting, as the following code would fail, and took me a while (comparing to earlier experiments) it would fail. The bellow code would work (trimmed down) if the get_loaded_program() was commented out, else it would fail with "No such file or
directory"

```
	if (get_loaded_program(&cfg_dumpopt.iface, &mode, &info) != 0) {
		pr_warn("ERROR: Specified interface must have an XDP program loaded!\n");
		return false;
	}

	//open_opts.attach_prog_fd = bpf_prog_get_fd_by_id(info.id); */
	open_opts.attach_prog_fd = bpf_prog_get_fd_by_id(57);
	trace_obj = open_bpf_file("xdpdump_bpf.o", &open_opts);

	error = bpf_object__load(trace_obj);
	if (error) {
			libbpf_strerror(error, error_msg, sizeof(error_msg));
			pr_warn("ERROR: Can't load eBPF object: %s(%d)\n",
				error_msg, error);
		}
```

**Comment by tohojo** [comment]
Wow, not sure *what* was going on there. I **hope** that particular bit of logic only ended up that way because I've been moving the code around so much...

Anyway, thanks for the fix, and sorry you had to spend a whole day debugging this :/

**Comment by chaudron** [comment]
> Anyway, thanks for the fix, and sorry you had to spend a whole day debugging this :/

No problem was some good time spend going over the libbpf/kernel code :)

**Comment by tohojo** [comment]
Eelco Chaudron <notifications@github.com> writes:

>> Anyway, thanks for the fix, and sorry you had to spend a whole day debugging this :/
>
> No problem was some good time spend going over the libbpf/kernel code
> :)

Ah, great! :)

**Pull request merged**
